name: Reformat

on:
  push:
    branches: [ master ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.ACTION_TOKEN }}

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.3.0
      with:
        php-version: '7.4'
      tools: php-cs-fixer

    - name: Code Reformatting...
      run: php-cs-fixer fix -v ./ --allow-risky=yes --config=./.php_cs

    - name: Commit Reformated Code
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: ${{ github.head_ref }}
        commit_message: Apply php-cs-fixer changes
